### PR TITLE
feat(migration): migrate to angular 10

### PR DESCRIPTION
**Pull request by aifrim**
The `component` schematic is now broken.
I would like to have it fixed within this issue https://github.com/fusionfabric/finastra-design-system/issues/241 because they basically cover the same fix, but in different parts.

DIsabled PR CI Linting due to:
```
fatal: path 'tsconfig.base.json' exists on disk, but not in 'remotes/origin/master'
```

Will make PR to update it after this reaches master.

### CODE REVIEW

**Comment by code2nguyen** [comment]
We must update peerDeps in https://github.com/fusionfabric/finastra-design-system/blob/feature/angular-10-migration/libs/angular-components/package.json

**Comment by code2nguyen** [comment]
can we use the lastest version of angular 10.0.7

**Comment by code2nguyen** [comment]
dont extend tsconfig.ts in tsconfig.app.ts ...example: https://github.com/fusionfabric/finastra-design-system/blob/feature/angular-10-migration/libs/angular-components/popover/tsconfig.lib.json

**Comment by aifrim** [comment]
> We must update peerDeps in https://github.com/fusionfabric/finastra-design-system/blob/feature/angular-10-migration/libs/angular-components/package.json

This was already part of the repo before hand. And it is the pattern we use.

**Comment by aifrim** [comment]
> can we use the lastest version of angular 10.0.7

Best I can do it 10.0.4 (@nrwl/nx@10.0.7)

**Pull request merged**
